import { ListInformations } from '@tcc/components/home/ListInformations'
import { Metadata } from 'next'
import { Suspense } from 'react'

export const metadata: Metadata = {
  title: 'Desenvolvimento de uma Horta Hidropônica automatizada e web monitorada',
  description: 'Generated by create next app',
}

export default function HomePage() {
  return (
    <Suspense>
      <ListInformations />
    </Suspense>
  )
}
